### ISSUE TITLE
Home:Better, have the content looks like the psd specs organize or justify if possible to look good

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/West-Coast-Swimming-Pool-Liners#12]
![home_03](https://cloud.githubusercontent.com/assets/11186386/7268199/36b5bed2-e8f9-11e4-8199-c94efa898e65.jpg)

**Comment by ramoncebudigital** [comment]
I don't see any problem here.

**Comment by dsigue** [comment]
You already done updating the content and its look okay now, the content are now similar to what the design looks like, so I mark this a Fixed.
