### ISSUE TITLE
Header page : Logo and phone number overlaps or gets distorted

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/West-Coast-Swimming-Pool-Liners#13]
![header page_03](https://cloud.githubusercontent.com/assets/11186386/7268413/b7f21fc0-e8fb-11e4-983d-a32e3ca23920.jpg)

**Comment by ramoncebudigital** [comment]
This is actually because of the "free call" added "(08)" so the  width will automatically extend and so with the "our products lorrem", let's just focus on the design specs Menu.

**Comment by dsigue** [comment]
Better the main menu title should have a limit in words to avoid distorted layout. Just like the way you do on "Case Studies "

**Comment by bernardtitan** [comment]
Issue was fixed and is confirmed as a valid bug as the area code in parentheses is required by the launchlist
