### ISSUE TITLE
Our Product page: Clipped text found on product items 

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/West-Coast-Swimming-Pool-Liners#23]
Note: Applicable also to Services page / Case studies - clipped text on IE 7 only
![product_04](https://cloud.githubusercontent.com/assets/11186386/7289914/7ce97596-e9a9-11e4-8f81-4cc3d25c5222.jpg)

**Comment by dsigue** [comment]
Problem still exist on IE 7 , Click text

**Comment by ramoncebudigital** [comment]
Working on my end, tried other computers.
Please wait to load the page or try to clear cache.

**Comment by dsigue** [comment]
I've try to verify the said issue on IE 7 from other machine, but it still the same error- clipped text. Been verified in 3 machines already, waiting to load the page and then try to do clear cache but its still the same, thanks.

**Comment by ramoncebudigital** [comment]
see screenshot
![screenshot_1](https://cloud.githubusercontent.com/assets/11186436/7383453/12854e84-ee52-11e4-8795-91207ec7b7c9.png)
