### ISSUE TITLE
Contact Us: Better update and change the format layout for the alert message something looks like on the attached screenshot for consistency to all projects

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/West-Coast-Swimming-Pool-Liners#32]
![contact us_04](https://cloud.githubusercontent.com/assets/11186386/7291596/186a1bf4-e9c5-11e4-932e-5083c85ad3ef.jpg)

**Comment by ramoncebudigital** [comment]
Christian said that it is ok not to implement this.
