### ISSUE TITLE
Mobile: Lead Ins: No Active state on lead Ins once click / tap 

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/West-Coast-Swimming-Pool-Liners#36]
Affected : All Mobile Device
![mobile lead ins_01](https://cloud.githubusercontent.com/assets/11186386/7292056/90f404e0-e9ca-11e4-85a1-61cf63c9c7e5.jpg)

**Comment by dsigue** [comment]
Problem still reproducible on Samsung S4 only

**Comment by ramoncebudigital** [comment]
Since we don't have actual device, we only using google emulator.
please see screenshot.
![screenshot_2](https://cloud.githubusercontent.com/assets/11186436/7383542/ed44b298-ee53-11e4-8344-c5b46072029a.png)

**Comment by ramoncebudigital** [comment]
working on our end. please try to clear cache.
