### ISSUE TITLE
Ipad device: 2nd and 3rd level submenus cannot be seen under Our Products main menu.

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/West-Coast-Swimming-Pool-Liners#41]
Affected : Ipad Device only
When click or tap on 2nd submenus it will not show or open.
![new main menu_01](https://cloud.githubusercontent.com/assets/11186386/7341305/10a65ec2-ecd2-11e4-9f38-ef30ff98ae53.jpg)

**Comment by ramoncebudigital** [comment]
waiting for the device
