### ISSUE TITLE
All Mobile Device : Distorted header page layout 

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/West-Coast-Swimming-Pool-Liners#45]
![new mobile header page_01](https://cloud.githubusercontent.com/assets/11186386/7342433/a356ec8c-ece6-11e4-9fc5-7ca7c4c0c354.jpg)

**Comment by dsigue** [comment]
Problem still exist on Ipad and Itouch 5 device

**Comment by ramoncebudigital** [comment]
working on our end.  
![screenshot_1](https://cloud.githubusercontent.com/assets/11186436/7582493/b25f3596-f8c0-11e4-927b-82224d407803.png)

**Comment by dsigue** [comment]
Problem verified still reproducible on Itouch 5 and Ipade device only.

![mobile header_01](https://cloud.githubusercontent.com/assets/11186386/7604620/c24869ca-f977-11e4-8ef5-727ae3e11cbd.jpg)

**Comment by ramoncebudigital** [comment]
please try again. no device for testing. :(

**Comment by dsigue** [comment]
The problem still exist even trying to do clear cache.Error still the same on Ipad Air and itouch 5

**Comment by ramoncebudigital** [comment]
ok, I will try again.
