### ISSUE TITLE
Home: Banner section : Clicking 3 times on the last image , the slick slider behavior changes. it will move back and forth not as continuous as it was as expected one by one.

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/West-Coast-Swimming-Pool-Liners#49]
![new home_02](https://cloud.githubusercontent.com/assets/11186386/7344933/f4ce571e-ed02-11e4-9f0d-0c2f794aeb78.jpg)

**Comment by dsigue** [comment]
Problem still exist, when clicking 3 times on the last image below banner section ,the slideshow will behave unlikely, it will show back and forth .

**Comment by ramoncebudigital** [comment]
This shouldn't be implemented like this, this is a mistake. The slider nav should be part of the gallery not in the Main slider as design specs. sorry for the wrong implementation.
