### ISSUE TITLE
Home: Banner section: Inconsistent behavior when clicking banner image on the right end than on the left end. 

### ISSUE THREAD

**Issue by dsigue** [titan-cebu/West-Coast-Swimming-Pool-Liners#8]
![banner_01](https://cloud.githubusercontent.com/assets/11186386/7267060/5cb48300-e8e7-11e4-8c91-f1d4151d4a91.jpg)

**Comment by ramoncebudigital** [comment]
This is the behavior of Slick plugin.
see it here.
http://kenwheeler.github.io/slick/
"Slider Syncing"
